name: Fetching Daily Market Prices from Kiamis

on:
  schedule:
    # 23:00 UTC every day (2:00 AM East Africa Time)
    - cron: '0 23 * * *'
  
  # manually click run for out-of-schedule runs
  workflow_dispatch: 

jobs:
  run-scraper:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip' # caches downloaded libraries

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          # Installs selenium, beautifulsoup4, pandas, and supabase from your list
          pip install -r requirements.txt 

      - name: Execute Market Price Script
        env:
          # uploads to supabase and notify the frontend to update the UI
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
        run: |
          python pipelines/market_prices.py